// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdnBbVYOYoykE8aXM9tKAg0Jw94rq11P8',
    appId: '1:105339821110:web:e6cae4a06cbbbf25ff8c97',
    messagingSenderId: '105339821110',
    projectId: 'embedded-project-32dca',
    authDomain: 'embedded-project-32dca.firebaseapp.com',
    databaseURL: 'https://embedded-project-32dca-default-rtdb.firebaseio.com',
    storageBucket: 'embedded-project-32dca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLl1dtmvnF_WFgVOhhkVH24ClU1kM_utQ',
    appId: '1:105339821110:android:52d767af068c14e3ff8c97',
    messagingSenderId: '105339821110',
    projectId: 'embedded-project-32dca',
    databaseURL: 'https://embedded-project-32dca-default-rtdb.firebaseio.com',
    storageBucket: 'embedded-project-32dca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaw2zZVvG3TsJPOeNx0KqMJDQwvGjD42s',
    appId: '1:105339821110:ios:90b27a27a68f34a2ff8c97',
    messagingSenderId: '105339821110',
    projectId: 'embedded-project-32dca',
    databaseURL: 'https://embedded-project-32dca-default-rtdb.firebaseio.com',
    storageBucket: 'embedded-project-32dca.firebasestorage.app',
    iosBundleId: 'com.example.irrigationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaw2zZVvG3TsJPOeNx0KqMJDQwvGjD42s',
    appId: '1:105339821110:ios:90b27a27a68f34a2ff8c97',
    messagingSenderId: '105339821110',
    projectId: 'embedded-project-32dca',
    databaseURL: 'https://embedded-project-32dca-default-rtdb.firebaseio.com',
    storageBucket: 'embedded-project-32dca.firebasestorage.app',
    iosBundleId: 'com.example.irrigationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdnBbVYOYoykE8aXM9tKAg0Jw94rq11P8',
    appId: '1:105339821110:web:25237ae43f9f9b6eff8c97',
    messagingSenderId: '105339821110',
    projectId: 'embedded-project-32dca',
    authDomain: 'embedded-project-32dca.firebaseapp.com',
    databaseURL: 'https://embedded-project-32dca-default-rtdb.firebaseio.com',
    storageBucket: 'embedded-project-32dca.firebasestorage.app',
  );
}