import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'firebase_options.dart'; // Make sure this file is generated by flutterfire_cli
import 'theme/app_theme.dart';
import 'services/stt_service.dart';
import 'services/notification_service.dart';
import 'screens/landing_screen.dart';
import 'widgets/stt_mic_button.dart';
import 'screens/home_screen.dart';
import 'screens/dashboard_screen.dart';
import 'screens/actuator_screen.dart';
import 'screens/ai_monitor_screen.dart';
import 'screens/alerts_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const SmartIrrigationApp());
  _initServices();
}

Future<void> _initServices() async {
  try {
    // Reset to AUTOMATIC mode on startup
    final modeRef = FirebaseDatabase.instance.ref('status/mode');
    final modeSnap = await modeRef.get();
    if (modeSnap.value?.toString() != 'AUTOMATIC') {
      await modeRef.set('AUTOMATIC');
    }
  } catch (_) {}

  try {
    await SttService.initialize();
  } catch (_) {}

  try {
    await NotificationService.initialize();
  } catch (_) {}
}

class SmartIrrigationApp extends StatelessWidget {
  const SmartIrrigationApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Irriga',
      theme: AppTheme.theme,
      home: const LandingScreen(destination: MainNavigation()),
    );
  }
}

class MainNavigation extends StatefulWidget {
  const MainNavigation({super.key});

  @override
  State<MainNavigation> createState() => _MainNavigationState();
}

class _MainNavigationState extends State<MainNavigation> {
  int _currentIndex = 0;

  final List<Widget> _screens = [
    const HomeScreen(),
    const DashboardScreen(),
    const ActuatorScreen(),
    const AiMonitorScreen(),
    const AlertsScreen(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _screens[_currentIndex],
      bottomNavigationBar: NavigationBar(
        selectedIndex: _currentIndex,
        onDestinationSelected: (index) {
          setState(() {
            _currentIndex = index;
          });
        },
        destinations: const [
          NavigationDestination(
            icon: Icon(Icons.home_outlined),
            selectedIcon: Icon(Icons.home),
            label: 'Home',
          ),
          NavigationDestination(
            icon: Icon(Icons.dashboard_outlined),
            selectedIcon: Icon(Icons.dashboard),
            label: 'Dashboard',
          ),
          NavigationDestination(
            icon: Icon(Icons.settings_remote_outlined),
            selectedIcon: Icon(Icons.settings_remote),
            label: 'Controls',
          ),
          NavigationDestination(
            icon: Icon(Icons.psychology_outlined),
            selectedIcon: Icon(Icons.psychology),
            label: 'AI Monitor',
          ),
          NavigationDestination(
            icon: Icon(Icons.notifications_none),
            selectedIcon: Icon(Icons.notifications),
            label: 'Alerts',
          ),
        ],
      ),
      floatingActionButton: const SttMicButton(),
    );
  }
}
